---
title: "Hamon"
format: html
editor: visual
---
```{r}
here::i_am("final graded lab.Rproj")
library(here)
library(ggplot2)
library(vroom)
library(dplyr)
library(tidyr)
library(lubridate)
```
# Introduction

## Study Organisation

Question 1
```{r}
courses <- vroom(here("data", "courses.csv"))
```
Question 2
```{r}
courses |>
  rename(
    `course name` = course,
    identifier = course_id,
    `number of exams` = nb_grades
  ) |>
  arrange(`course name`) |>
  knitr::kable()
```

## Students

Question 3
```{r}
students <- vroom(
  here("data", "students.csv"),
  col_types = cols(
    id = col_integer(),
    group = col_integer(),
    birth_date = col_date(),
    sex = col_factor()
  )
)
students
```

## Grades
Question 4
```{r}
grades <- vroom(
  here("data", "grades.csv"),
  delim = ";",
  na = "$",
  col_types = cols(
    id = col_integer(),
    course_id = col_integer(),
    grade = col_double()
  )
)
grades
```

# Student population analysis

Question 5
```{r}
students |>
  count(group) |>
  arrange(group) |>
  ggplot(aes(x = group, y=n)) +
  geom_col()
```

Question 6
```{r}
students |>
  count(group, sex) |>
  arrange(group) |>
  ggplot(aes(x = factor(group), y = n, fill = sex)) +
  geom_col()
  geom_col() +
  labs(
    title = "gender balance in groups"
  )
```

Question 7
```{r}
students <- students |>
  mutate(
    age = time_length(today() - birth_date, unit = "year")
  )

students <- students |>
  mutate(
    age = round(age)
  )

ggplot(students, aes(x = age)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color="white") +
  labs(
    title = "distribution of students' ages",
    x = "age in years",
    y = "nb of students"
  )
```
Question 8
```{r}
students |>
  group_by(group) |>
  summarize(
    median_age = median(age)
    ) |>
  arrange(group) |>
  knitr::kable()
```

